apps/playlists/urls.py
from django.urls import path

from . import views


app_name = "playlists"
urlpatterns = [
    path("playlists/distributions/<uuid:distribution_id>.m3u8",
        views.DistributionPlaylistView.as_view(),
        name="distribution"),
    path("playlists/streams/<uuid:stream_id>.m3u8",
        views.StreamPlaylistView.as_view(),
        name="stream")
]

apps/watch/urls.py
from django.urls import path

from . import views


app_name = "watch"
urlpatterns = [
    path("", views.LiveStreamListView.as_view(), name="list_streams"),
    path("watch/<uuid:id>", views.WatchByStreamIdView.as_view(), name="watch"),
    path("watch/<uuid:id>/<str:distribution_name>",
        views.WatchByStreamIdView.as_view(), name="watch"),
    path("watch/<str:name>", views.WatchByNameView.as_view(), name="watch"),
    path("watch/<str:name>/<str:distribution_name>",
        views.WatchByNameView.as_view(), name="watch")
]

streamkit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('frontend-api/', include('apps.frontend_api.urls')),
    path('', include('apps.streams.urls')),
    path('', include('apps.playlists.urls')),
    path('', include('apps.watch.urls')),
]

apps/watch/models.py
from django.db import models

# Create your models here.

apps/watch/views.py
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404

from apps.streams.models import Stream, Distribution


class WatchView(TemplateView):
    template_name = "watch/watch.html"

    def get_context_data(self, **kwargs):
        """
        Get the stream and then an associated distribution for the stream.
        """
        stream = self._get_stream()
        distribution: Distribution = get_object_or_404(stream.distributions,
            name=self.kwargs.get("distribution_name", "source"))

        context = super().get_context_data(**kwargs)
        context['stream'] = stream
        context['distribution'] = distribution
        return context

    def _get_stream(self) -> Stream:
        """
        Returns a stream object. This is a dummy method which should be
        overriden by a subclass.
        """
        raise NotImplementedError


class WatchByStreamIdView(WatchView):
    def _get_stream(self) -> Stream:
        """
        Attempts to get the stream by using the UUID kwarg provided from
        the URL pattern.
        """
        return get_object_or_404(Stream,
            id=self.kwargs['id'])


class WatchByNameView(WatchView):
    def _get_stream(self) -> Stream:
        """
        Attempts to get the stream using the stream's name.
        """
        return get_object_or_404(Stream.objects.exclude(name=""),
            name=self.kwargs['name'])


class LiveStreamListView(TemplateView):
    """
    Very basic listing view which shows currently live streams.
    """    
    template_name = "watch/list_streams.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['live'] = Stream.objects.filter(status="live")
        context['vods'] = (Stream.objects
                .filter(status="finished")
                .order_by("-stopped"))
        return context

apps/watch/templates/watch/list_streams.html
<div>
    <ul>
        <h2>Live</h2>
        {% for stream in live %}
            <li>
                <a href="{% url 'watch:watch' id=stream.id %}">{{ stream.name }}</a>
            </li>
        {% endfor %}

        <h2>VODs</h2>
        {% for stream in vods %}
            <li>
                <a href="{% url 'watch:watch' id=stream.id %}">{{ stream.name|default:stream.key }}</a>
            </li>
        {% endfor %}
    </ul>
</div>

apps/watch/templates/watch/watch.html
<!-- CSS  -->
<link href="https://vjs.zencdn.net/7.2.3/video-js.css" rel="stylesheet">


<!-- HTML -->
<div align="middle">
    <video id='hls'  class="video-js vjs-default-skin" width="1600" height="900" controls>
        <source type="application/x-mpegURL" src="{% url 'playlists:distribution' distribution.id %}">
    </video>
</div>

<div>
    <h2>Distributions</h2>
    <ul>
        {% with current_distribution=distribution %}
            {% for distribution in stream.distributions.all %}
                <li>
                    {% if distribution == current_distribution %}
                        {{ distribution.name }}
                    {% else %}
                        <a href="{% url 'watch:watch' id=stream.id distribution_name=distribution.name %}">
                            {{ distribution.name }}
                        </a>
                    {% endif %}
                </li>
            {% endfor %}
        {% endwith %}
    </ul>
</div>


<!-- JS code -->
<!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
<script src="https://vjs.zencdn.net/ie8/ie8-version/videojs-ie8.min.js"></script>
<script src="https://unpkg.com/browse/@videojs/http-streaming@1.11.2/dist/videojs-http-streaming.min.js"></script>
<script src="https://vjs.zencdn.net/7.2.3/video.js"></script>

<script>
    var player = videojs('hls');
    player.play();
</script>